* Recipes

** Soups
*** Buenas Noches Black Bean Soup
**** Ingredients
- 1 large onion, chopped
- 2 cups celery, chopped
- 2 cups chopped carrots
- 4 cloves garlic, chopped
- 1 tblsspoon ground cumin
- 2 teaspons chili powder
- 1/4 teaspoon black pepper
- 6 cups water or stock
- 1 tablespoon mrs dash
- 6 cups cooked (or 4 15-ouce cans) of black beans [divided]
- 1 jar mild picante sauce or salsa low sodium
- 2 cups frozen corn, thawed
- 1 1/2 cups diced tomates
**** Instructions
In large soup pot combine onion, celery, carrots, garlic, cumin, chili powder, black pepper, watter, mrs dash and 3 cups beans. Bring to a boil, reduce heat and simmer for 15 min

Place remaining 3 cups beans and picante sauce/salsa in blender or food processor and blend on high until smooht. Stir into soup mixture along with corn and tomatoes.

Simmer for an additoinal 15 min.
*** Carrot and Red Lentil Soup
**** Ingredients
- 3-4 Large sweet onions, chopped
- 2 cloves garlic, chopped
- 4 cups carrot Juice
- 4 cups low-sodium or no salt veggie browth
- 1 pound red lentils
- 5 ounces baby kale or spinich
- 2 tablespooons fresh lemon juice to taste
- 1/4 cup chopped parsley
**** Instructions
- Heat 2-3 tablespoons water in soup pot and water saute onions and garlic until tender.
- Add corrot juice, veggie browth and lentils.
- Bring to a boild, lover heat, and simmer, covered until lentils are soft (50-60 min)
- Stir  in baby kale or spinach and heat uneil wilted
- Add lemon juice and chopped parsley
*** Mushroom and Barley Soup
**** Ingredients
- 1 medium onion, chopped
- 1 cup chopped carrots
- 1/2 cup chopped celery
- 3 cloves garlic, minced
- 20 ounces mushrooms sliced
- 1 teaspons liquid aminos or soy sauce
- 1 cup whole grain barley
- 8 cups low-sodium or no salt veggie browth
- 1/4 teaspoon ground pepper
- 1/2 taspoon dried thyme
- 2 cups arugala
**** Instructions
- Heat 1/4 cup water in large soup pot and water saute onions, carrots, celery, and garlic until softened, about 6 min
- Add mushrooms and aminos and cook until mushrooms release their juices (about 5 min)
- Add Barley, veggie broth, black pepper, and thyme, bring to a boil.
- Reduice heat, cover, and simmer for 60 min or until barley is tender.
- Stir in arugula and heat until wilted.
*** Kale and White Bean Stew
**** Ingredients
- 2 bunches of kale, tough stems removed and leaves coarsely chopped
- 1/4 cup water
- 1 medium onion, chopped
- 2 cloves garlic, minced
- mrs dash to taste
- black pepper
- crushed red pepper to taste
- 3 cups cooked or (2 15-ounce cans of white beans)
- 3 cups diced tomatoes
- 2 cups veggie broth, low sodium or no salt added or more if needed to achieve desired consistency
**** Instructions
- Add kale and water to a soup pot, cover and cook over medium heat for 10 minutes or until kale is tender, stirring occasionally
- Add onion, garlic, seasoning blend, black pepper and red pepper
- Continue to cook, uncovered, for 5-7 minutes
- Add beans, tomatoes and vegetable broth and bring to boil. Reduce heat and simmer covered for 15-20 minutes, stirring occasionally.
  
** Dinners
*** Roasted Cauliflower with Chickpeas, tomatoes and spinach
**** Ingredients
- 1 head cauliflower, cored and cut into small florets
- 1 medium onion, chopped
- 2 cloves garlic, minced
- 1 teaspoon fennel seeds
- 1 1/2 teaspon ground cumin
- 1/4 teaspoon black pepper
- pinch fo ground cayenne pepper, or more to taste
- 26 ounces packaged chopped tomatoes
- 1 1/2 cups cooked or 1 (15-ounce) can low sodium or no salt chickpeas drained
- 1 (5-ounce) package fresh baby spiach or baby kale
- whole grean such as polenta, quinoa, farro or wild rice (optional)
**** Instructions
- Preheat oven to 400f
- Place cauliflower on a lightly oiled baking pand and bake 20 minutes or until cauliflower is tneder (stirring freequently)
- Heat 2-3 tablespoons water in a large saute pan and water-saute onions until they soften. Add garlic, fennel seeds, cumin and black/red pepper.
- Continue to cook for 1 minute, adding water as needed
- Add tomatoes, chickpeas, roasted cauliflower, and 1/2 cup water: bring to boil
- reduice heat and simmer until liquid has slightly thickened, about 15 min.
- Fold in spinach and cook until just wilted about 1-2 minutes
- if desired serve over whole grain
*** Stir Fried Rice
**** Ingredients
- Oil
- Eggs
- Onion
- Garlic
- Various veg (options below):
  - Broccoli
  - Bell pepper
  - Basil
  - Peas
  - Carrot
- Sauce:
  - Soy Sauce
  - Chilli sauce
  - Spice (peppers or da bomb)
  - lime juice
  - terryaki

** Full Recipes
*** Vegan Caviar (Macedonian ajvar)
I learned this Macedonian "vegan caviar" from Beryl Shereshewsky's youtube cooking show -- an episode on toast. If you haven't checked out her show, I absolutely love it. Here's the episode: [https://www.youtube.com/watch?v=IStY1BVoUKA](https://www.youtube.com/watch?v=IStY1BVoUKA)

Ajvar is so good, feels fancy, and I could have eaten with a spoon.

Here's how to make it:

Take:

- 2 red bell peppers
- 1 eggplant

Roast (475 for 30 minutes) until black (not totally black but you know, like black spots) Cool. Take off skin.

Puree in food processor with

- 1 garlic clove, smashed

Reduce in nonstick until thickened (30 minutes) and then add:

- 1 ½ tsp white wine vinegar
- ⅛ tsp ground black pepper-
- up to a 1 tsp of salt

Eat cold or hot.

Sprinkle with parsley if you're taking a picture for reddit.

*** Enchalada Bake
**** Ingredients
- 1 cup uncooked quinoa, rinsed
- 2 cups water
- 1 tablespoon olive oil
- 1 small onion, diced
- 3 cloves garlic, minced
- 1 jalapeño, seeds and ribs removed,diced
- 1 red bell pepper, seeds removed, diced
- 1 orange or yellow bell pepper, seeds removed, diced
- 1 cup corn frozen kernels
- Juice of 1 small lime
- 1 teaspoon ground cumin
- 1 tablespoon chili powder
- 1/3 cup chopped cilantro
- Salt and pepper, to taste
- 30 oz canned black beans, rinsed and drained
- 2 cups [[*Enchilada Sauce][Enchilada Sauce]]
- 2 cups shredded Mexican cheese
- Toppings: Sliced green onions, avocado, sour cream, cilantro
**** Instructions
1. Preheat the oven to 350 degrees F. Grease a 9×13 baking dish with cooking spray and set aside.
2. Add quinoa and water to a medium saucepan and bring to a boil over medium heat. Boil for 5 minutes. Turn the heat to low and simmer for about 15 minutes, or until water is absorbed. Remove from heat and fluff with a fork. Cover quinoa and set aside.
3. In a large skillet, heat the tablespoon of olive oil over medium-high heat. Add the onion, garlic, and jalapeño. Sauté until softened, about 5 minutes. Add in the peppers and corn. Cook for about 3-4 minutes. Add the lime juice, cumin, chili powder, and cilantro. Stir to combine. Season with salt and pepper, to taste.
4. In a large bowl, add the cooked quinoa and black beans. Add the sautéed vegetable mixture and stir to combine. Pour in the enchilada sauce and stir. Add ½ cup shredded cheese.
5. Pour the black bean and quinoa mixture into the prepared baking dish. Top with remaining shredded cheese. Cover the pan with foil. Bake for 20 minutes, then remove foil. Bake an additional 10 minutes, or until the cheese is melted and edges are bubbling. Remove from the oven, and let cool for 10 minutes. Garnish with toppings, if desired. Serve warm.
6. Note-this recipe freezes well! If you need the recipe to be gluten-free make sure you use a gluten-free enchilada sauce. We like to serve it with tortilla chips.

*** Enchilada Sauce
**** Ingredients
- 3 tablespoons vegetable oil
- 3 tablespoons flour (can use gluten-free flour or cornstarch)
- 2 tablespoons chili powder (can use less for a milder sauce)
- 1 teaspoon ground cumin
- ½ teaspoon kosher salt
- Pinch of cayenne pepper, optional
- 1/4 teaspoon dried oregano
- 1/4 teaspoon onion powder
- 1 clove garlic, minced
- 2 tablespoons tomato paste
- 2 cups vegetable broth
**** Instructions
1. In a large saucepan, heat the vegetable oil over medium heat. Add the flour and whisk for one minute. Add all the spices and garlic; stir for about a minute. Whisk in the tomato paste, then slowly pour in the vegetable broth, whisking constantly until the mixture is smooth.
2. Let the sauce simmer over medium low heat for 10-12 minutes or until slightly thickened. The sauce will thicken as it cools. Taste and season with additional salt, if necessary.

** Links
- [[https://www.instagram.com/reel/CbqFQJcvFOs/?utm_medium=copy_link][Korean Steamed Eggs]]
- [[https://alexiaraye.com][Alexia Raye - Ray Cronise's Daughter]]
- [[https://sweetsimplevegan.com/2020/01/one-pot-lentil-mushroom-bolognese-sauce/#tasty-recipes-24948-jump-target][Lentil Bolagnaise]]
- [[https://thekoreanvegan.com/spicy-crunchy-garlic-tofu-kkampoong-tofu/][Spicy Garlic Tofu]]
- [[https://www.reddit.com/r/PlantBasedDiet/comments/sft0an/zunka/][Zunka - A Chickpea based recipe]]
- [[\[https://www.cearaskitchen.com/fluffy-oil-free-hummus/\](https://www.cearaskitchen.com/fluffy-oil-free-hummus/)][Fluffy Hummus (Oil Free)]]
- [[https://www.twopeasandtheirpod.com/black-bean-and-quinoa-enchilada-bake/][Black Bean and Enchilada Quinoa Bake]]
- [[https://youtube.com/shorts/AEHFB1iotKY?si=iEOCLnJYC4Vaq1_r][Fresh Salsa in a Molcajete]]
